### ISSUE TITLE
Configurable payload type

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#116]
Allow to configure payload type in sender (command line and public API). Payload type defines number of channels, sample format, and rate.

**Comment by dshil** [comment]
I think it'd be reasonable to have an option to see a list of currently supported payload types, wouldn't it?

**Comment by gavv** [comment]
> I think it'd be reasonable to have an option to see a list of currently supported payload types, wouldn't it?

Agree. Currently they're few, so we can just print them in --help.

> How would we distinguish L16/mono and L16/stereo? In RFC2586 it's represented as one type.

https://tools.ietf.org/html/rfc3551#section-6

```
               10   L16         A           44,100       2
               11   L16         A           44,100       1
```

We already have these constants: https://github.com/roc-project/roc/blob/develop/src/modules/roc_rtp/headers.h#L31

> I'll use a predefined list of known encoding formats from RFC3551

Yes, this is the correct RFC. See the link above to the concrete section.

**Comment by gavv** [comment]
First, we need to resolve issue #86.

Then we should add rtp::FormatMap::find_best(), which finds the best payload type for the user-provided channel set, sample rate, and encoding. And then use it in the API and tools to pick an appropriate encoding for given parameters

After that we can add more encoding options to API and tools, e.g. mono or surround sound, non-PCM encodings, etc.

To support encodings not listed in RTP AVP, we need dynamic payload type support (via SDP). It allows the sender to describe its payload parameters.

**Comment by gavv** [comment]
Steps.

Internals:

- [ ] FormatMap::add_format
- [ ] Configurable channel set (#86)
- [ ] Frame encoding (#547) 

API:

- [ ] roc_packet_encoding
- [ ] roc_format
- [ ] roc_channel_layout
- [ ] roc_media_encoding
- [ ] roc_sender_config: frame_encoding, packet_encoding
- [ ] roc_receiver_config: frame_encoding
- [ ] roc_context_register_encoding

CLI:

- [ ] sample spec parser
- [ ] remove --rate
- [ ] add --io-encoding
- [ ] add  --payload-id & --payload-encoding

**Comment by gavv** [comment]
Will be covered in #608
