### ISSUE TITLE
Failover to local audio

### ISSUE THREAD

**Issue by BeyondChrispy** [roc-streaming/roc-toolkit#313]
It would be great to implement a feature that would allow playback of a locally stored audio file(s) on a Roc receiver in the event that the internet connection that Roc is using fails (or other similar failure of the stream).  Once the internet connection is restored and the Roc stream is working again it goes back to streaming.

I'd like to use Roc as a Studio to Transmitter link solution for a radio station - this feature would be ideal.

**Comment by gavv** [comment]
Hi!

There is currently no such thing as internet connection, but we know the number of currently active sessions at the receiver, one session per sender. So we could add an option to specify the input file or device that should be used when there are zero active sessions. It's technically possible.

A few questions:

* Why do you need this? Just curious. I'm not familiar with radio stuff.
* Are you talking about roc-recv command-line tool or about the C API?
* Any ideas how to name the option? (Maybe there is a common term for this).

**Comment by BeyondChrispy** [comment]
Hi,
At my radio station, we use a Band 1 analog radio transmitter/receiver to link the studio to the transmitter.  As a backup, we have a streaming receiver which constantly plays the radio station's web stream in case the analog link fails (the transmitter automatically switches to the streaming receiver).  The unit that does this is now rather old and I am looking to replace it with a higher quality solution.  If the stream receiver cannot play the stream (for example, internet connection failure or a stream problem at the studio), it plays an MP3 file from a USB drive until the stream is restored.  This allows us to keep on transmitting if there is no power at our studio (a very rare occurrence, but due to broadcasting laws in the UK, we have to provide protection against this type of failure).

I would run this (most likely) on a Rasperry Pi at both ends (send and receive).

We could call the feature 'Backup Audio'?

I'm no coder, I just thought I'd suggest the feature :)

**Comment by gavv** [comment]
Thanks, I see. "Backup audio" sounds good, I think.

I'll add this to 0.2 milestone, which we're currently working on.

The backup file is supposed to be played from the beginning every time when we lost connection, right?

**Comment by BeyondChrispy** [comment]
Hi Victor,

Yes, that sounds good.  Thanks so much for your input.

Chris.

**Comment by gavv** [comment]
@BeyondChrispy I've implemented this feature. It's pushed to `develop` branch. Could you test it?

Example:

```
$ roc-recv -vv -s rtp+rs8m::10001 -r rs8m::10002 --backup file:./somefile.wav
```

```
$ roc-send -vv -s rtp+rs8m:127.0.0.1:10001 -r rs8m:127.0.0.1:10002 \
  -i file:./anotherfile.wav
```

Manual page for roc-recv from `develop`: https://github.com/roc-project/roc/blob/develop/docs/sphinx/manuals/roc_recv.rst (grep for "backup").

Note that in `develop`, the command-line syntax changed a bit. It uses URIs for files and devices.

I think `develop` wont be merged in `master` very soon because 0.2 release is still in progress. In general, `develop` is considered unstable, however the current commit 56daef3fffc40d123ef6764734172b62e9a46b0a is known to work good. I recommend you to stick on this commit instead of using `develop` tip.

**Comment by BeyondChrispy** [comment]
Thank you Victor!  I have had a busy time of late, but I'll endeavor to get
it tested as soon as I can!

Chris.

**Comment by gavv** [comment]
Thanks, no hurry.

**Comment by gavv** [comment]
Closing this, feel free to reopen or create a new issue if you'll have troubles.
