### ISSUE TITLE
Improve integration tests for public API

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#328]
Currently we have 3 [integrations tests](https://github.com/roc-project/roc/blob/d61d81ace3fd443d966c21b519e2cc08861f61bb/src/tests/roc_library/test_sender_receiver.cpp#L429) for our [C API](https://roc-streaming.org/toolkit/docs/api.html):

* without FEC
* with Reed-Solomon FEC and without losses
* with Reed-Solomon FEC and with losses

We need to cover more parameter combinations:

- [x] Use single context for sender and receiver, or use separate contexts.
- [x] Use one sender per receiver, or connect multiple senders to receiver (sequential version).
- [ ] Use one sender per receiver, or connect multiple senders to receiver (parallel version).
- [x] Use one receiver, or create multiple receivers sharing one context, and connect a sender to each receiver.
- [x] Use Reed-Solomon or LDPC-Staircase FEC schemes, with and without losses.
- [ ] Enable or disable packet interleaving.
- [ ] Use different resampler profiles.
- [ ] Use different clock sources (external or internal).
- [ ] Test a few different presets of FEC block size, latency, and breakage detection parameters. For example, one low latency preset and one high latency preset.

Before adding more tests, it would be also nice to extract Context, Sender, Receiver, and Proxy from test_sender_receiver.cpp into separate files in src/tests/roc_library (i.e. test_context.h, test_sender.h, and so on).

This work can be split into multiple PRs, one or a few tests per PR.

**Comment by CleverShovel** [comment]
I would like to try write these tests.

**Comment by gavv** [comment]
@CleverShovel Great, you're welcome!

**Comment by CleverShovel** [comment]
@gavv Is this normal that in roc_library directory there are files like test_context.cpp, test_sender.cpp and others and I will add test_context.h and others but they will not related to these cpp?

**Comment by gavv** [comment]
Good catch. Since this issue was created, the file layout in tests was changed a bit. According to the new layout, these files should be named like `roc_library/test_helpers/context.h`, `roc_library/test_helpers/sender.h`, etc. See, for example, tests for roc_pipeline or roc_audio.

**Comment by CleverShovel** [comment]
@gavv Does each item from the list in issue description mean concrete tests or only a parameter to combine?

**Comment by gavv** [comment]
Well, it's just a list of features to be covered somehow. Obviously, we can't create a test for every possible combination of these features because there were too much tests. So, likely, we should create one or a few test for every specific item. E.g., for `Enable or disable packet interleaving` we can create one test covering both cases or two separate tests, one w/o interleaving, one w/ interleaving. That's not a strict requirement, though. For example, if we already have another test covering transfer w/o interleaving, there is no need to duplicate it.

**Comment by CleverShovel** [comment]
@gavv As far as I can see for parallel test of multiple senders and one receiver I should add another one `roc_endpoint` and `roc_receiver` in `Receiver` class and additionally adjust while cycle in method `Receiver::run()`. Am I right?

**Comment by gavv** [comment]
You can connect multiple senders to the same endpoint(s). The receiver will mix them. You need to adjust the received stream checking to expect the stream mixed from multiple senders.

The hard thing here is that you don't known how the streams from different senders are shifted. One possible way to deal with it is to make the first sender produce stream like 10, 20, 30, ..., and the second sender 1, 2, 3, ... Then you'll read from the receiver something like 25, 36, 47, ... and from that you can deduce the original sequences of both senders and check them separately.

**Comment by gavv** [comment]
`multiple_senders_one_receiver_sequential` is failing quite often, I disabled it for now.

https://travis-ci.org/github/gavv/roc/jobs/671349254

![fail2](https://user-images.githubusercontent.com/8436629/78509041-dd9a5b80-7793-11ea-8a2f-9bc56170b302.png)

https://travis-ci.org/github/gavv/roc/jobs/671349250

![fail1](https://user-images.githubusercontent.com/8436629/78509050-e8ed8700-7793-11ea-84e8-ebfe99bb60fe.png)

@CleverShovel Could you please take a look?

**Comment by CleverShovel** [comment]
@gavv ok, I'll check it more carefully

**Comment by CleverShovel** [comment]
@gavv When I debugged the test in [`Receiver::run()`](https://github.com/roc-project/roc/blob/develop/src/tests/roc_library/test_helpers/receiver.h#L95) I get these data in `rx_buff`:
![Снимок экрана от 2020-04-06 21-47-09](https://user-images.githubusercontent.com/37588466/78589609-88248400-7851-11ea-81d5-0368573b8cdd.png)
![Снимок экрана от 2020-04-06 21-49-29](https://user-images.githubusercontent.com/37588466/78589622-8d81ce80-7851-11ea-80e7-a491ddbbd7af.png)
`Receiver` expect data in range (0, 1) but there can be very small numbers as well as very big numbers and nan. Can I add some function that check that received number in range (0, 1) ?
Also I think that variable `wait_for_signal` not very useful here. One time the tests were failed because of this variable. When in `prev_sample` number from the previous frame and `wait_for_signal = true` value of `prev_sample` isn't set to beginning of current frame. Unfortunately reproduce this error I can't.

**Comment by gavv** [comment]
> Receiver expect data in range (0, 1) but there can be very small numbers as well as very big numbers and nan.

This looks very strange. If receiver produces samples out of range [0; 1], it's a bug. But are you sure that you're debugging it correctly? How did you get the numbers on screenshot?

> Can I add some function that check that received number in range (0, 1) ?

Yes, adding such a check is legit and makes sense.

> Also I think that variable wait_for_signal not very useful here.

IIRC it was added for reason. Maybe @alexandremgo can provide some details on this.

**Comment by gavv** [comment]
I think the problem with `multiple_senders_one_receiver_sequential` is that we're not waiting until the receiver will fully process the samples from the first sender before starting the second one.

I guess we should change the flow to the following:

* run first sender
* wait until receiver starts producing all zeros for some period of time
* run second sender

**Comment by gavv** [comment]
BTW, note that this test likely will work incorrectly under a debugger because of its real-time nature. (Though receiver should not produce numbers out of [-1; 1] range anyway).

**Comment by gavv** [comment]
An interesting detail: both failures on travis were on sample `#3999`.

**Comment by gavv** [comment]
@CleverShovel Hi, do you have any further plans on this?

**Comment by CleverShovel** [comment]
@gavv Sorry for long delay, I'm was busy. I try to find time for this by the end of this month.

**Comment by gavv** [comment]
Great!

**Comment by gavv** [comment]
Unassigning so that someone can continue the work during hacktoberfest. @CleverShovel feel free to let me know if you want to be re-assigned though.

**Comment by gavv** [comment]
I've created separate issues for remaining tests:

* https://github.com/roc-streaming/roc-toolkit/issues/557
* https://github.com/roc-streaming/roc-toolkit/issues/558
* https://github.com/roc-streaming/roc-toolkit/issues/559
* https://github.com/roc-streaming/roc-toolkit/issues/560
