### ISSUE TITLE
Add Ubuntu 20.04 to CI

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#353]
We already have 14.04, 16.04, and 18.04, and now want to add 20.04 as well.

Issue #307 gives an idea how to add a new distro to CI.

The build instructions should be the same as for 18.04, so there is no need to update documentation.

**Comment by Villaquiranm** [comment]
Hello, I would like to work in this if it's still free

**Comment by gavv** [comment]
Thanks, you're welcome.

**Comment by gavv** [comment]
After fixing the build on `rocproject/travis-ubuntu:20.04`, we should also switch `rocproject/travis-checks` base from ubuntu 19.04 to 20.04, since 19.04 image doesn't work anymore.

**Comment by gavv** [comment]
We also need to add gcc-10 and clang-10 to ubuntu 20.4 dockerfile and travis script. We'll also have to fix warnings on clang 10. Both of this can be done separately.

**Comment by gavv** [comment]
I've added gcc-10 and clang-10 to the dockerfile.

**Comment by gavv** [comment]
I've created a new docker hub org and renamed the images a bit, see details here: https://www.freelists.org/post/roc/Docker-images-for-Android-build,3

We'll migrate travis build to the new images in upcoming days.

`travis-checks` image is not present in the new org; instead, I've added valgrind, clang-format, and other necessary tool to env-ubuntu:20.04.

**Comment by gavv** [comment]
Merged. @Villaquiranm thanks.
