### ISSUE TITLE
Implement version-checking macros and functions

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#383]
Add the following macros to the public API allowing to retrieve the compile-time version of the toolkit:

```
#define ROC_VERSION_MAJOR ...
#define ROC_VERSION_MINOR ...
#define ROC_VERSION_PATCH ...
```

Also add a function allowing to retrieve runtime version (which may be different, i.e. has higher minor or patch version):

```
// get version numbers
// fills major, minor, and patch if they're non-NULL
void roc_version(int* major, int* minor, int* patch);
```

These definitions should be added to `src/library/include/roc/version.h` and properly commented.

Additional changes:

* update the API reference at `docs/sphinx/api/reference.rst`
* add unit test for roc_version() to `src/tests/roc_library`
* get rid of the `.version` file and instead used macros from public API

Regarding the last change. Currently we have `.version` file at the project root, defining the current toolkit version. SConstruct reads this file and passes it to compiler as `-DROC_VERSION=...`, making it available for our internal modules.

Now we should remove this file. SConstruct should instead parse `src/library/include/roc/version.h` file and use major, minor, and patch version defined there to form the `ROC_VERSION` macro for internal modules.

**Comment by ssfuen** [comment]
hi, I'd like to work on this

**Comment by gavv** [comment]
Sure, thanks, you're welcome.

**Comment by gavv** [comment]
@ssfuen Hi, do you still have plans on this?

**Comment by gavv** [comment]
Landed!
