### ISSUE TITLE
Employ build hooks in toolchain docker images

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#388]
We've recently merged a mechanism, based on [docker build hooks](https://docs.docker.com/docker-hub/builds/advanced/#build-hook-examples),  for building multiple variants of a single dockerfile and pushing them to multiple docker tags.

For details, see here:

* [documentation](https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/development/continuous_integration.rst#docker-hub-build-hooks)
* [discussion](https://github.com/roc-streaming/dockerfiles/pull/4)

It's currently used in [`env-android`](https://github.com/roc-streaming/dockerfiles/tree/master/images/env-android) and [`toolchain-linux-android`](https://github.com/roc-streaming/dockerfiles/tree/master/images/toolchain-linux-android) images.

We should use this new mechanism for other cross-compilation images:

* `toolchain-arm-bcm2708hardfp-linux-gnueabi`
* `toolchain-arm-linux-gnueabihf`
* `toolchain-aarch64-linux-gnu`

Instead of duplicating dockerfiles for each tag and changing hard-coded parameters, we should use a single dockerfile for each image, parameterized using ARG mechanism, plus images.csv file which will be used by hooks to populate ARGs.

Dockerfiles are located here: https://github.com/roc-streaming/dockerfiles/tree/master/images

Documentation can be found here: https://roc-streaming.org/toolkit/docs/development/continuous_integration.html

**Comment by jsomwaru** [comment]
I'm interested in the project. Do you think I can take this issue. I'm a little rusty at C++ so I think this would be a good start for me while i get up to speed with the project.

**Comment by gavv** [comment]
@jsomwaru Sure, you're welcome.

**Comment by jsomwaru** [comment]
Would you like this done for other images as well instead of just the ones mentioned above? The Ubuntu images could also be managed the same way.

**Comment by gavv** [comment]
Dockerfiles for different ubuntu tags have different package sets, so I think using a single dockerfile wouldn't be beneficial here: it will anyway have conditions for each supported tag.

**Comment by gavv** [comment]
Thanks!
