### ISSUE TITLE
Add CentOS 8 to CI

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#391]
Currently our env-centos dockerfile is based on CentOS 7: https://github.com/roc-streaming/dockerfiles/blob/master/images/env-centos/Dockerfile

It would be nice to add a tag for CentOS 8, and if necessary fix the build on it.

Tags should be added as sub-directories like here: https://github.com/roc-streaming/dockerfiles/tree/master/images/env-ubuntu

Then we should update .github/workflows/build.yml and CI scripts: https://github.com/roc-streaming/roc-toolkit/tree/master/scripts/ci/linux-x86_64 to build both 7 and 8 tags.

Finally, we should update docs:

* https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/building/user_cookbook.rst (update only if CentOS 8 will have different build instructions)

* https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/portability/supported_platforms.rst (update list of supported CentOS versions)

* https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/development/continuous_integration.rst (add new image to the table)

**Comment by EkanshBhatnagar** [comment]
I could do that.

**Comment by gavv** [comment]
Great, you're welcome!

**Comment by gavv** [comment]
I've created a new docker hub org and renamed the images a bit, see details here: https://www.freelists.org/post/roc/Docker-images-for-Android-build,3

We'll migrate travis build to the new images in upcoming days.

So `travis-centos` should be now replaced with `env-centos` which can be found here:

* https://github.com/roc-streaming/dockerfiles/tree/master/images/env-centos
* https://hub.docker.com/r/rocstreaming/env-centos

**Comment by gavv** [comment]
@EkanshBhatnagar Hi, do you still have plans on this?

**Comment by gavv** [comment]
Unassigning so that someone could pick it up.

**Comment by gavv** [comment]
CentOS is discontinued now.
