### ISSUE TITLE
Run tests in Android simulator in CI

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#396]
Currently we have Android build in Travis, but it doesn't run unit tests. It is defined [here](https://github.com/roc-streaming/roc-toolkit/blob/61a31b5887829630d0d82259587ad3a1bc14cd48/.travis.yml#L93-L107).

It would be nice to run tests on Travis using Android simulator.

We already have `env-android` docker image that provides Android SDK and emulator, and a helper script to manage simulator devices:

* [documentation](https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/development/continuous_integration.rst#android-environment)
* [dockerfile](https://github.com/roc-streaming/dockerfiles/tree/master/images/env-android)
* [dockerhub page](https://hub.docker.com/r/rocstreaming/env-android)
* [helper script](https://github.com/roc-streaming/dockerfiles/blob/master/images/env-android/device.sh)

This image is used in our java bindings to run java tests in simulator, which was implemented here: https://github.com/roc-streaming/roc-java/pull/21.

Now we want to employ a similar approach for our C++ tests. In java bindings we're using gradle, and to run C++ tests we can use adb as mentioned here: https://github.com/roc-streaming/roc-java/pull/21#issuecomment-643603332

Travis scripts are located here: https://github.com/roc-streaming/roc-toolkit/tree/develop/scripts/travis

An example of running tests manually from travis scripts can be [found here](https://github.com/roc-streaming/roc-toolkit/tree/develop/scripts/travis/linux-arm). Those scripts also run tests in an emulated environment, but they use qemu instead of android simulator.

Related: #390.

**Comment by MatteoArella** [comment]
I can easily work on this

**Comment by gavv** [comment]
Great!

**Comment by gavv** [comment]
Done, except failing tests on i686: #424.

**Comment by gavv** [comment]
Just caught an error on x86_64:

```
--- installing system image android-29;default;x86_64

Warning: An error occurred while preparing SDK package Intel x86 Atom_64 System Image: Connection reset.

The command "scripts/travis/android.sh API=29 NDK_VERSION=21.1.6352462 ABI=x86_64 scripts/travis/android/linux-android.sh" exited with 1.
```

https://travis-ci.org/github/gavv/roc-toolkit/jobs/729580567

@MatteoArella any ideas?

**Comment by MatteoArella** [comment]
> Just caught an error on x86_64:
> 
> ```
> --- installing system image android-29;default;x86_64
> 
> Warning: An error occurred while preparing SDK package Intel x86 Atom_64 System Image: Connection reset.
> 
> The command "scripts/travis/android.sh API=29 NDK_VERSION=21.1.6352462 ABI=x86_64 scripts/travis/android/linux-android.sh" exited with 1.
> ```
> 
> https://travis-ci.org/github/gavv/roc-toolkit/jobs/729580567
> 
> @MatteoArella any ideas?

Connection reset on download seems unrelated to #419 PR but it seems rather a travis network connectivity problem. Did you encounter this problem before or it is the first time?
If you prefer, as you suggested time ago, we can try caching android sdk inside distfiles repo and see if it is an achievable solution.

**Comment by gavv** [comment]
> Connection reset on download seems unrelated to #419 PR but it seems rather a travis network connectivity problem

Oh, I see. I though it's connection to emulator, but if it's just an error during download, I agree it's unrelated.

> Did you encounter this problem before or it is the first time?

This is the first time.

>  If you prefer, as you suggested time ago, we can try caching android sdk inside distfiles repo and see if it is an achievable solution.

Let's indeed close this issue. I'll add a comment regarding SDK to #405.
