### ISSUE TITLE
SCons rebuilds generated files twice

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#407]
I expect this issue will require diving deep into [scons](https://scons.org/) internals, a Python-based build system we use. If you're interested, welcome aboard :)

We use GNU gengetopt to generate command-line parsers. We have three gengetopt files:

```
src/tools/roc_conv/cmdline.ggo
src/tools/roc_recv/cmdline.ggo
src/tools/roc_send/cmdline.ggo
```

For each of them, scons generates `cmdline.c` file and includes it into build. Here is where it's implemented:

* https://github.com/roc-streaming/roc-toolkit/blob/develop/src/SConscript#L188
* https://github.com/roc-streaming/roc-toolkit/blob/develop/site_scons/site_tools/roc/commands.py#L122

It works, but there is a small problem.

When scons is invoked first time, it generates and builds everything as expected:

```
$ scons -Q --build-3rdparty=openfec,cpputest,google-benchmark,pulseaudio --compiler=clang \
  --enable-debug --enable-werror --enable-tests --enable-benchmarks --enable-examples  \
  --enable-pulseaudio-modules test
<...>
      GGO   src/tools/roc_conv/cmdline.ggo
      GGO   src/tools/roc_recv/cmdline.ggo
      GGO   src/tools/roc_send/cmdline.ggo
<...>
       CC   build/x86_64-pc-linux-gnu/clang-10.0.0-debug/tools/roc_conv/cmdline.c
       CC   build/x86_64-pc-linux-gnu/clang-10.0.0-debug/tools/roc_recv/cmdline.c
       CC   build/x86_64-pc-linux-gnu/clang-10.0.0-debug/tools/roc_send/cmdline.c
<...>
     TEST   roc_core
<...>
```

When scons is invoked **second time**, for some reason it rebuilds `cmdline.c` files once more:

```
$ scons -Q --build-3rdparty=openfec,cpputest,google-benchmark,pulseaudio --compiler=clang \
  --enable-debug --enable-werror --enable-tests --enable-benchmarks --enable-examples  \
  --enable-pulseaudio-modules test
       CC   build/x86_64-pc-linux-gnu/clang-10.0.0-debug/tools/roc_conv/cmdline.c
       CC   build/x86_64-pc-linux-gnu/clang-10.0.0-debug/tools/roc_recv/cmdline.c
       CC   build/x86_64-pc-linux-gnu/clang-10.0.0-debug/tools/roc_send/cmdline.c
     TEST   roc_core
<...>
```

Starting from the third invocation, they're not rebuilt anymore:

```
$ scons -Q --build-3rdparty=openfec,cpputest,google-benchmark,pulseaudio --compiler=clang \
  --enable-debug --enable-werror --enable-tests --enable-benchmarks --enable-examples  \
  --enable-pulseaudio-modules test
     TEST   roc_core
<...>
```

So the problem is that the files are rebuilt with no reason at the second scons invocation.

We already have an [attempt of a workaround](https://github.com/roc-streaming/roc-toolkit/blob/develop/site_scons/site_tools/roc/commands.py#L150-L163), but it seems it doesn't work or works only partially (see also [here](https://gavv.github.io/articles/sconsign-bug/)).

Probably this is a bug in scons, or maybe our GenGetOpt() function is not quite correct.

If it's a bug, we should create a minimal reproducer and report to upstream. If possible, we should apply some workaround to our code.

We also use ragel to generate C++ sources and compile them, similarly to gengetopt (search for Ragel() function), however we don't have such problem with ragel. Maybe the difference is caused by header files scanner.

**Comment by dvzrv** [comment]
I have seen this issue before with mixxx and they were never able to fix it and instead moved away from scons.
The latter is something I can recommend in general. Scons has sooooo many flaws and is generally too old to be refactored/ improved sensibly.

I would recommend meson or cmake for this project. Personally I have more experience with the former than the latter and do think its syntax is much more straight forward than that of cmake.

**Comment by gavv** [comment]
I've removed my workaround and the issue disappeared: 244fedc1d4e3caa2ce63fc1beeb8b98bc166297b

Seems that it helped on old scons versions and hurts on recent versions. So now closing this.
