### ISSUE TITLE
Generate PDF and EPUB from sphinx documentation

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#409]
We have [sphinx](https://www.sphinx-doc.org/en/master/) documentation, from which we automatically generate HTML and publish it on our website.

In addition to the website for online browsing, it would be nice to allow the user to download PDF and EPUB for offline reading.

We should configure sphinx to generate those two files and display links to the PDF and EPUB in the left sidebar, somewhere at the bottom of the table of contents. Probably sphinx can include such links automatically, otherwise we can do it by ourselves.

Links:

* [documentation source code](https://github.com/roc-streaming/roc-toolkit/tree/develop/docs/sphinx)
* [sphinx config](https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/conf.py)
* [published HTML](https://roc-streaming.org/toolkit/docs/)
* [website repo](https://github.com/roc-streaming/roc-streaming.github.io)

**Comment by Nazi-pikachu** [comment]
Hey! I would like to work on this issue please assign it to me if not already assigned

**Comment by gavv** [comment]
Great, you're welcome.

**Comment by gavv** [comment]
@Nazi-pikachu Hi, do you still have plans on this?

**Comment by Nazi-pikachu** [comment]
@gavv Sorry for the long gap, I am bit new with open source and Github so it is taking me a lot of time to fix this can you help me out on how to approach the above issue i have started by looking the documentation of sphinx but i was unsure on how to implement the PDF and EPUB version of the documentation in the code also how to add the button in the website for the same any help will be much appreciated.

**Comment by gavv** [comment]
@Nazi-pikachu no worries, take your time.

**Comment by ivsntejesh** [comment]
Check out this post- https://gist.github.com/alfredodeza/7fb5c667addb1c6963b9.
If it might help.

**Comment by gavv** [comment]
@Nazi-pikachu Hi, do you still have plans on this?

**Comment by gourishbiradar** [comment]
Hi @gavv, I have made changes to generate the PDF file, please reassign this issue to me
