### ISSUE TITLE
Use thread local storage in fast_random()

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#410]
Currently, [core::fast_random()](https://github.com/roc-streaming/roc-toolkit/blob/da0383488b087e632d6fbcf9bd99be00670173c0/src/modules/roc_core/target_posix/roc_core/fast_random.cpp#L38) is implemented using pthread_once + pthread_mutex. This approach works, but creates an additional contention point between real-time threads, which is better to be avoided.

Instead of using pthread_once + pthread_mutex, we can implement that function using thread local storage (pthread_key_create and friends). We can just use a separate PRNG for every thread.

**Comment by Prg1005** [comment]
Hi @gavv I would like to work on this issue, please let me know.

**Comment by gavv** [comment]
@Prg1005 Great, you're welcome!

**Comment by pvimal816** [comment]
> Instead of using pthread_once + pthread_mutex, we can implement that function using thread local storage (pthread_key_create and friends). We can just use a separate PRNG for every thread.

Can we use `__thread` keyword to have thread local seed. Then I think we don't need pthread_key_create.

**Comment by gavv** [comment]
> @gavv 
> > Instead of using pthread_once + pthread_mutex, we can implement that function using thread local storage (pthread_key_create and friends). We can just use a separate PRNG for every thread.
> 
> Can we use `__thread` keyword to have thread local seed. Then I think we don't need pthread_key_create.

Regarding __thread, see my last comment in PR.

**Comment by gavv** [comment]
I've created a new issue: #426.
