### ISSUE TITLE
Mac build error

### ISSUE THREAD

**Issue by CaseyGuanSun** [roc-streaming/roc-toolkit#418]
I am building roc-toolkit on Mac book pro.
but there are errors about it: 
: scons -Q
then print this error:
AttributeError: 'SConsEnvironment' object has no attribute 'SourceCode':
roc-toolkit/SConstruct", line 55:
    env.SourceCode('.', None)

**Comment by gavv** [comment]
Thanks for reporting! This function was deprecated in recent scons. Fixed in develop and master, could you please check it?

**Comment by gavv** [comment]
Feel free to re-open if you'll have the issue again.

**Comment by tleb** [comment]
This issue is present in the latest released version (0.1.15) but not on master (fixed by commit abdfbb94df98fe88be4dd92ca587500126558411 I believe). Is a new release planned soon?

Thanks!

**Comment by gavv** [comment]
I've recently tagged 0.2.0, which includes this fix.
