### ISSUE TITLE
armhf cross compile error

### ISSUE THREAD

**Issue by demon36** [roc-streaming/roc-toolkit#425]
when I try to cross compile for my raspberrypi 4 using the docker command described at https://gavv.github.io/articles/roc-tutorial/, I get the following error:
`
scons: *** [.clang-checks] ValueError : unsupported pickle protocol: 5
`

also having prebuilt binaries would help a lot

**Comment by b247** [comment]
I also had some problems with using docker for cross-compiling roc for armv7.
But I succeeded by using the manual toolchain approach.
Here: https://github.com/b247/b247/tree/master/roc-toolkit-pulseaudio-armv7-binary-files, you can find both binary files and the toolchain approach used.

**Comment by demon36** [comment]
thanks for help, I found it too complicated so I tried trx, which seems to do the job quite well, also available in debian repos

**Comment by b247** [comment]
For me, roc-streaming does the perfect job; It have PulseAudio modules and FEC. It takes a few minutes to be up and running in both my Ubuntu desktop (from where I can use pavucontrol) and my headless Debian 9 arm RPi 3.
I'm quite impressed with the audio quality and wish to send my gratitude to Victor for that. Copy/paste some already used by me shell commands (or as a last resource just copy some binary files) should not be so difficult to accomplish but indeed at some point, it may vary depending on the use case.

**Comment by gavv** [comment]
Hi, sorry for late reply!

```
scons: *** [.clang-checks] ValueError : unsupported pickle protocol: 5
```

This usually means that you've used scons with different python versions on the same repo (e.g. on host and in docker container). Just cleaning the working copy should fix the problem. E.g. run `scons -c` on host and only then run build using docker.

I'll take a look, maybe we can handle it programmatically or at least report more meaningful error message.

**Comment by gavv** [comment]
Regarding prebuilt binaries, I think the proper way to do it is to create packages for popular distros. Such packaging requires a maintainer, someone who is familiar with the distro, is using Roc on it, and have some time for this. From my side, I'll be happy to provide any help and open to suggestions.

BTW, someone once started working [on a package for Archlinux](https://github.com/roc-streaming/roc-toolkit/issues/334), but it's not done yet.

**Comment by gavv** [comment]
@b247 Thanks for your kind words!

**Comment by gavv** [comment]
Fixed this in `develop` by using separate scons db files for different python versions:

```
env.SConsignFile(os.path.join(
    env.Dir('#').abspath, '.sconsign%s%s.dblite' % sys.version_info[0:2]))
```

Now switching between python versions should work well.
