### ISSUE TITLE
Make fast_random() lock-free

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#426]
_Last revised: Oct 2023_

Currently, [core::fast_random()](https://github.com/roc-streaming/roc-toolkit/blob/da0383488b087e632d6fbcf9bd99be00670173c0/src/modules/roc_core/target_posix/roc_core/fast_random.cpp#L38) is implemented using pthread_once + pthread_mutex. This approach works, but creates an additional contention point between real-time threads, which is better to be avoided.

Another problem with current implementation is that it uses nrand48(), which is not completely thread-safe (see comments in the source code).

To improve this, we can adopt a simple atomic-based lock-free PRNG algorithm. As a bonus, it will be fully portable, instead of POSIX-specific (given that we already have portable atomics in roc_core).

The implementation can be very simple. For example, we can use `mulberry32` from [this SO answer](https://stackoverflow.com/questions/17035441/looking-for-decent-quality-prng-with-only-32-bits-of-state/52056161#52056161) and replace `state += 0x6D2B79F5` with an atomic add-and-fetch. Here is a real-world example of lock-free PRNG: [lfds710_prng.h](https://github.com/liblfds/liblfds/blob/master/liblfds/liblfds7.1.0/liblfds710/inc/liblfds710/lfds710_prng.h).

See #420 for background.

**Comment by GoldenBug** [comment]
In your issue description you mention that the current implementation uses both pthread_once + pthread_mutex, however in your linked file I only see your usage of pthread_mutex.

Is that the correct branch/commit/file?
Or do I misunderstand something when you say the current implementation uses pthread_once.

**Comment by gavv** [comment]
@GoldenBug You're right, my bad. We use only mutex; pthread_once was employed in #420, but it wasn't merged.

**Comment by roopmukherjee** [comment]
Will a distribution work? Perhaps similar to https://stackoverflow.com/a/21238187.

**Comment by stevenzhu94** [comment]
Hi all. @gavv the current implementation returns uniformly distributed pseudo random numbers, so the solution mentioned by @roopmukherjee would be a good replacement, no?

**Comment by gavv** [comment]
@roopmukherjee @stevenzhu94

Using C++11 random would require to have separate implementation for old non-C++11 compilers (which we still support), and I'd like to avoid this. Also, I'm not sure if C++11 thread_local is lock-free, are you aware of that?

Since replicating implementation from linked SO answer or lfds710_prng is rather simple, compatible with old compilers, and is guaranteed to be lock-free, for now I think this is the best way to go.

**Comment by ForeverASilver** [comment]
@gavv 
I’d like to help with this!
I looked at the SO answer mentioning mulberry32 but going to the github [link](https://gist.github.com/tommyettinger/46a874533244883189143505d203312c) the developer mentions it isn’t equi-distributed, so provides a different implementation with the caveat that it produces every number only once before repeating.

Is there any preference here for what should be implemented?

**Comment by gavv** [comment]
@ForeverASilver 

> I’d like to help with this!

Welcome, let me know if you wish to be assigned.

> I looked at the SO answer mentioning mulberry32 but going to the github [link](https://gist.github.com/tommyettinger/46a874533244883189143505d203312c) the developer mentions it isn’t equi-distributed, so provides a different implementation with the caveat that it produces every number only once before repeating.

Good catch! Thanks for looking into this.

That different implementation is splitmix32, mentioned first in the linked SO answer. (I guess that gist is actually the original source for it).

So far I saw only three PRNGs with 32-bit state which claims decent quality and looks feasible to be implemented lock-free: splitmix32, mulberry32, and xorshift32 (and its variations). BTW here is one more good overview that mentions them all: https://github.com/bryc/code/blob/master/jshash/PRNGs.md.

splitmix32 and mulberry32 both can be easily made lock-free: they perform only one operation with their 32-bit state (add constant). xorshift32 is not so convenient, it performs several xors and shifts on the state.

There are numerous generators with 64-bit state, but we run on platforms that don't have 64-bit atomics, so they are not good candidates as well.

Since mulberry32 has problems you mentioned, it seems that splitmix32 is so far the best choice for us. I think adding 100% portable lock-free RNG will be a good start despite the mentioned caveat. If desired, we always can add better platform-specific alternatives later.

**Comment by ForeverASilver** [comment]
@gavv
I'll give it a shot!

looking at lfds it seems how they go about implementing a lock-free fetch and add is to define an atomic add function based on gcc version and platform. This seems to be the best way going about it due to the platform support and the supported compiler versions.

**Comment by gavv** [comment]
We already have portable wrapper, you need to include `roc_core/atomic_ops.h` and use `AtomicOps::fetch_add_seq_cst()` on state.

PRNG state can be just global variable in fast_random.cpp.

**Comment by gavv** [comment]
Landed!
