### ISSUE TITLE
roc sink input module fails to load

### ISSUE THREAD

**Issue by QuditWolf** [roc-streaming/roc-toolkit#448]
I am on rpi 4, I installed roc using the online documentation.
Pulseaudio woks fine except for when I try to load the roc sink input module it says Module initialization failed...

``` 
$pactl load-module module-roc-sink-input 
Failure: Module initialization failed 
```

PS: i built it using the ``` --enable-pulseaudio-modules ``` option.

What could be the reason/fix for the above?
Thanks

**Comment by QuditWolf** [comment]
I think the following is the issue : pulseaudio -vvv
```
E: [pulseaudio] ltdl-bind-now.c: Failed to open module module-roc-sink-input.so: module-roc-sink-input.so: cannot open shared object file: No such file or directory
E: [pulseaudio] module.c: Failed to open module "module-roc-sink-input".
```
how can i fix this?

Please pardon me for any evident mistake...

**Comment by QuditWolf** [comment]
It got it to work by compiling it using docker for arm platforms.. and then copying the librabraries and modules....
Somehow compiling there on debian rpi doesnt work.....

**Comment by gavv** [comment]
Sorry for delay. I don't have rpi4 ATM and can't really suggest anything without more information, hopefully full build logs & pulseaudio logs could give some insight. If you'd like to investigate it, feel free to reopen the issue and provide any additional information you could acquire.
