### ISSUE TITLE
enable back SO_REUSEADDR to support systemd socket activation

### ISSUE THREAD

**Issue by twojstaryzdomu** [roc-streaming/roc-toolkit#449]
I've been using patched roc software for some time now in a systemd socket activated environment.

While pulseaudio could run with the module-roc-sink-input module in the background on the remote host, it may be sometimes convenient to activate the remote pulseaudio server with an incoming UDP packet, sent by a local pulseaudio instance. The remote pulseaudio instance is configured to load the module-roc-sink-input module. It makes sense in low CPU resource environments like raspberrypi zero where a loaded module-roc-sink-input module is observed to take ~20% CPU. Keeping it running constantly when not needed throttles performance.

The SO_REUSEADDR flag needs to be set to allow concurrent port access by the systemd listener and the roc module to bind to the UDP port. The SO_REUSEADDR flag is enabled for unicast communication solely to allow multiple UDP processes binding to roc port (10001 UDP).

The workflow is as follows:
1. systemd socket is first started listening on UDP port 10001 with 'ReusePort=true', enabling concurrent binds for UDP & TCP ports, on remote host.
2. user loads pulseaudio module-roc-input on local host, sending traffic to remote host on UDP port 10001
3. systemd socket is triggered by an incoming packet, activating a pulseaudio instance on  remote host
4. pulseaudio loads module-roc-sink-input with the SO_REUSEADDR flag enabled on remote host. Without SO_REUSEADDR enabled in the compiled code and with systemd socket listening, subsequently loading module-roc-sink-input would fail.

A command line option to enable SO_REUSEADDR for the module would be a neater solution.

Sample systemd socket listener:
```
[Unit]
Description=Pulseaudio sound server socket
Conflicts=pulseaudio.socket
Requires=sound.target
After=sound.target

[Socket]
Priority=6
Backlog=5
# Required for concurrent access to TCP/UDP ports by two or more sources (local systemd listener & remote pulseaudio client)
ReusePort=true
ListenStream=4713
# roc UDP port
ListenDatagram=10001

[Install]
WantedBy=sockets.target
```

Patch to enable back SO_REUSEADDR for the UDP port:
```
--- a/src/modules/roc_netio/target_libuv/roc_netio/udp_receiver_port.cpp	2019-09-03 09:14:12.894487010 +0200
+++ b/src/modules/roc_netio/target_libuv/roc_netio/udp_receiver_port.cpp	2019-09-03 09:20:34.546696880 +0200
@@ -57,9 +57,7 @@
     handle_initialized_ = true;
 
     unsigned flags = 0;
-    if (address_.multicast() && address_.port() > 0) {
-        flags |= UV_UDP_REUSEADDR;
-    }
+    flags |= UV_UDP_REUSEADDR;
 
     int bind_err = UV_EINVAL;
     if (address_.version() == 6) {
--- a/src/modules/roc_netio/target_libuv/roc_netio/udp_sender_port.cpp	2019-09-03 09:14:12.894487010 +0200
+++ b/src/modules/roc_netio/target_libuv/roc_netio/udp_sender_port.cpp	2019-09-03 09:20:49.262704521 +0200
@@ -61,9 +61,7 @@
     handle_initialized_ = true;
 
     unsigned flags = 0;
-    if (address_.multicast() && address_.port() > 0) {
-        flags |= UV_UDP_REUSEADDR;
-    }
+    flags |= UV_UDP_REUSEADDR;
 
     int bind_err = UV_EINVAL;
     if (address_.version() == 6) {

```

**Comment by gavv** [comment]
Hi, thanks for report and patch! The use case looks legit. We should investigate whether it should be enabled unconditionally or by an option, and what should be the default. At least one case where we don't want SO_REUSEADDR is when we're using ephemeral ports (see [here](https://gavv.github.io/articles/ephemeral-port-reuse/)).

**Comment by gavv** [comment]
I've added `--reuseaddr` option to CLI tools which enables SO_REUSEADDR, as well as corresponding API calls.

See https://github.com/roc-streaming/roc-toolkit/pull/520

Docs are updated as well.

Closing, feel free to reopen if needed!

**Comment by gavv** [comment]
Tagged 0.2.3 with this fix included.
