### ISSUE TITLE
documentation: Can you document missing dipendencies clearly ?

### ISSUE THREAD

**Issue by souravdas142** [roc-streaming/roc-toolkit#451]
You need to clearly document all dependecies at [building/user_cookbook](https://roc-streaming.org/toolkit/docs/building/user_cookbook.html), I know These all are documented at [building/dependencies](https://roc-streaming.org/toolkit/docs/building/dependencies.html) but still can make someone confuse, so better also add at [building/dependencies.html](https://roc-streaming.org/toolkit/docs/building/dependencies.html) here.

or you can also give a reference for dependencies from   [building/user_cookbook](https://roc-streaming.org/toolkit/docs/building/user_cookbook.html) to  [building/dependencies](https://roc-streaming.org/toolkit/docs/building/dependencies.html) 

The missing dependencies are - 

`curl`, `wget` - To download other dependencies by scons
`doxygen`, `graphviz` - To build docs
`python3-sphinx`, `python3-breathe` - To build manual pages
`pulseaudio` - (Who are using `pulseaudio`) To autodetect `PA` version by scons

**Comment by gavv** [comment]
Hi, thanks, I'll revise the docs.

BTW, not 100% sure about master branch, but in develop branch documentation is not built by default and doxygen / graphviz / python3-sphinx / python3-breathe are not needed for regular users.

Also, curl and wget are used as fallbacks only, in case if we can't download package using builtin python facilities, which may happen in some environments. IIRC they are not needed on most distros.

**Comment by pelim** [comment]
` brew install speexdsp`

is missing in user cookbook

**Comment by gavv** [comment]
I think docs are up-to-date now. Feel free to reopen if I'm missing something.
