### ISSUE TITLE
some errors about building roc-toolkit

### ISSUE THREAD

**Issue by houqinghui** [roc-streaming/roc-toolkit#457]
![image](https://user-images.githubusercontent.com/13465812/127851796-c5288bfc-f86a-4585-aa6f-eef74720fa1b.png)
please help me to build roc-toolkit.
at first  i came accross the error "cannot  find the libudev.h"

**Comment by gavv** [comment]
Hi, sorry, seems this message got lost.

If by any chance this is still relevant, please reopen and provide the command you were running and full build log.
