### ISSUE TITLE
Can't make 'ltdl-2.4.6'

### ISSUE THREAD

**Issue by ZSenZhang** [roc-streaming/roc-toolkit#469]
Hi, I am trying to build up the toolkit but faces "Can't make ltdl-2.4.6' error. I faces this issue while using "scons -Q --enable-pulseaudio-modules --build-3rdparty=openfec,pulseaudio". My OS version is ubuntu 20.04.

**Comment by gavv** [comment]
Hi! Could you please post the full build output?

**Comment by gavv** [comment]
Closing for now, feel free to reopen if needed.
