### ISSUE TITLE
Build error on macOS

### ISSUE THREAD

**Issue by puyral** [roc-streaming/roc-toolkit#476]
I'm trying to build and install `roc-toolkit` on a 13" M1 MacBook Pro on macOS Monterey 12.4.
Unfortunately, as I follow the wiki's instructions, I get the following error:
```bash
$ sudo scons -Q --build-3rdparty=openfec install
  INSTALL   /usr/local/include/roc
  INSTALL   /usr/local/lib/libroc.0.1.dylib
    FIXUP   /usr/local/lib/libroc.0.1.dylib
/Library/Developer/CommandLineTools/usr/bin/install_name_tool: fatal error: file not in an order that can be processed (dyld chained fixups out of place): /usr/local/lib/libroc.0.1.dylib
scons: *** [install] Error 1
```

**Comment by gavv** [comment]
Hi, thanks for reporting.

I recently pushed a big update from develop to master and tagged v0.2.0 release.

Could you retry on master or 0.2.0? Probably the issue is fixed.

**Comment by puyral** [comment]
Hello,

I just tried again on the updated master, and it compiled successfully!

**Comment by gavv** [comment]
Thanks!
