### ISSUE TITLE
build-3rdparty.py: remove default value for `variant` variable

### ISSUE THREAD

**Issue by adrianopol** [roc-streaming/roc-toolkit#491]
This script is used for building 3rd-party dependencies when a user passes `--build-3rdparty=dep1,dep2,...` option to the `scons` utility like:
```
scons -Q --build-3rdparty=openfec --enable-tests test
```
`variant` argument is mandatory when running the script (see line `variant = sys.argv[4]` and below), but the function `makeflags()` has empty default empty-string value for it (which is used for example for libuv dependency):
```
def makeflags(workdir, toolchain, env, deplist, cflags='', ldflags='', variant='', pthread=False):
```
This is a bug.

## Acceptance criteria

- `variant` should never be assumed something different from `debug` or `release` in build-3rdparty.py script
- some CI builds may be affected by this change; they should also be fixed

## Implementation details

- fix `makeflags()` signature (remove default value for `variant` argument)
- look for all places where it is called and pass global `variant` variable explicitly

**Comment by gavv** [comment]
Because of this issue `--enable-debug-3rdparty` does not work for all dependencies

**Comment by gavv** [comment]
Seem that current code does not have this problem.

**Comment by gavv** [comment]
https://github.com/roc-streaming/roc-toolkit/blob/229a74eb3ba2229017203de63fe8798813e87185/scripts/scons_helpers/build-3rdparty.py
