### ISSUE TITLE
Add `selftest` target to Scons and run it in CI

### ISSUE THREAD

**Issue by adrianopol** [roc-streaming/roc-toolkit#511]
Now, we have a new command to run self-tests for building scripts:
```
python scripts/scons_helpers/build-3rdparty.py --self-test
```
This should be added as a new step in CI pipeline and be called as `scons selftest`.

## Acceptance criteria

- [ ] `scons selftest` runs all self-tests (there is only file currently); `GetPythonExecutable()` should be used to call a correct Python interpreter executable
- [ ] this action is run on every source code change (once for each pipeline)
- [ ] docs updated (scons options and developer cookbook pages)

**Comment by gavv** [comment]
"doc-tests" sounds a bit misleading, because other doc* targets are related to documentation. 

What do you think about "selftest" I suggested above?

**Comment by adrianopol** [comment]
agree, let's call it `selftest

**Comment by gavv** [comment]
Landed.
