### ISSUE TITLE
replace all `%` with `.format()` in python code

### ISSUE THREAD

**Issue by adrianopol** [roc-streaming/roc-toolkit#512]
https://docs.python.org/2/library/stdtypes.html#str.format :
> format(*args, **kwargs)
> This method of string formatting is the new standard in Python 3, and should be preferred to the % formatting described in String Formatting Operations in new code.

**Comment by adrianopol** [comment]
PRs:
- #513
- #517

**Comment by oliveselow87** [comment]
@maximeborges

**Comment by oliveselow87** [comment]
#537

**Comment by oliveselow87** [comment]
#531

**Comment by oliveselow87** [comment]
@jdeblese

**Comment by maximeborges** [comment]
> @maximeborges  

Why are you pinging me there?
And what is the point of your four comments here?

**Comment by maximeborges** [comment]
> @maximeborges  

Why are you pinging me there?
And what is the point of your four comments here?

**Comment by gavv** [comment]
Seems this task really excites the minds

#534

**Comment by gavv** [comment]
Landed

**Comment by oliveselow87** [comment]
Duplicate of #
<details><summary>Details</summary>
<p>



</p>
</details>
