### ISSUE TITLE
Add docker image with pre-installed sphinx

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#561]
We need to create docker image for reproducible documentation builds.

First, we should add new image `env-sphinx` to dockerfiles repo: https://github.com/roc-streaming/dockerfiles

It should have 3 python modules pre-installed:

- sphinx
- breathe
- sphinxemoji

And also system packages:

- scons
- doxygen
- graphviz

Python module versions should be freezed using pip and saved to requirements.txt.

Then we need to switch web site build github action to use new docker image for building documentation: https://github.com/roc-streaming/roc-streaming.github.io/blob/source/.github/workflows/build.yaml

Note: docker should be used only for building step, but not for the publishing step.

Documentation for our CI and docker images is available here: https://roc-streaming.org/toolkit/docs/development/continuous_integration.html

**Comment by nolan-veed** [comment]
I can do this.

**Comment by nolan-veed** [comment]
I've done the image bit.

For the https://github.com/roc-streaming/roc-streaming.github.io/blob/source/.github/workflows/build.yaml change, I think we need some scripts from the main repo, so that we can do docker image runs to build the documentation.

Or shall I just write one here?

**Comment by gavv** [comment]
Thanks!

> I think we need some scripts from the main repo, so that we can do docker image runs to build the documentation.

Do you mean scripts/ci_checks/docker.sh? I think we can just copy command from it.

**Comment by nolan-veed** [comment]
(Was away for 2 weeks - continuing on this.)

**Comment by gavv** [comment]
Landed!
