### ISSUE TITLE
Support NO_COLOR and FORCE_COLOR env variables

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#564]
Upgrade CLI tools (roc-send, roc-recv, roc-copy) to take into account two environment variables when color mode is auto:

- disable colors when NO_COLOR variable is set to non-empty string

- enable colors when FORCE_COLOR variable is set to a positive integer

See https://no-color.org/

It should be implemented here: https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_core/target_posix_pc/roc_core/console.cpp

Also add "ENVIRONMENT VARIABLES" section to manual pages and document these variables: https://github.com/roc-streaming/roc-toolkit/tree/develop/docs%2Fsphinx%2Fmanuals

Like here: https://man7.org/linux/man-pages/man1/less.1.html

After updating rst files, please regenerate manual pages as described here: https://roc-streaming.org/toolkit/docs/building/developer_cookbook.html#building-documentation

And add generated pages to commit.

**Comment by nolan-veed** [comment]
This is cool. I'll do.

**Comment by gavv** [comment]
Thanks, landed.
