### ISSUE TITLE
Print list of supported protocols

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#578]
roc-recv and roc-send tools have option to print list of supported audio backends and formats:

```
$ roc-recv --list-supported
supported schemes for audio devices and files:
  pulse:// alsa:// oss:// file://

supported formats for audio files:
  .aifc .aiffc .aiff .aif .al .au .snd .avr .cdda .cdr .cvsd .cvs .cvu .dat
  .dvms .vms .f32 .f64 .gsrt .hcom .htk .ima .la .lu .maud .prc .s8 .s16
  .s24 .s32 .sf .ircam .sln .smp .sndr .sndt .sox .sph .nist .8svx .txw
  .u8 .sou .fssd .u16 .u24 .u32 .ul .voc .vox .wav .wavpcm .amb .wve .xa
  .amr-nb .anb .amr-wb .awb .caf .fap .flac .gsm .lpc10 .lpc .mat4 .mat
  .mat5 .mp3 .mp2 .paf .pvf .sd2 .sds .vorbis .ogg .w64 .wv .xi
```

We need to teach them to include information about supported protocols as well, something like this:

```
supported network protocols:
  audiosrc: rtp:// rs8m+rtp:// ldpc+rtp://
  audiorpr: rs8m:// ldpc://
  audioctl: rtcp://
```

Here, each line has [interface name](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_address/interface.h) (`audiosrc` and others), and then lists [protocols](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_address/protocol.h) supported by this interface.

Steps:

* add two new methods to [ProtocolMap](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_address/protocol_map.h): `get_supported_interfaces(core::Array<Interface>&)` (returns list of all interfaces for which there is at least one protocol) and `get_supported_protocols(Interface, core::StringList&)` (returns list of all protocols for given interface), similar to what we have in [BackendDispatcher](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_sndio/backend_dispatcher.h) for supported schemes and formats

* add new function `address::print_supported(const ProtocolMap&)` (prints list of interfaces and protocols as described above), similar to [sndio::print_supported](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_sndio/print_supported.h)

* update [roc-recv](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/tools/roc_recv/main.cpp) and [roc-send](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/tools/roc_send/main.cpp) to invoke `address::print_supported()` after `sndio::print_supported()`

* update help message in `.ggo` files and [manual pages](https://github.com/roc-streaming/roc-toolkit/tree/develop/docs/sphinx/manuals)

**Comment by Hrick87** [comment]
Hi, after reading over the issue and relevant links to code, I've decided this would be a good first contribution for me. If its still available can you assign me this task? Thank you.

**Comment by gavv** [comment]
Sure, you're welcome, thanks!
