### ISSUE TITLE
Implement memory guards in heap arena

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#583]
[core::HeapArena](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_core/heap_arena.h) implements IArena interface using regular heap (malloc and free).

It would be nice to implement for HeapArena the same safety checks as described here for Pool: #582 (with the only difference that heap arena has "chunks" instead of "slots").

**Comment by nolan-veed** [comment]
I'll do this one too.

**Comment by nolan-veed** [comment]
This one can be closed now?

**Comment by gavv** [comment]
IIRC we didn't implement ownership check yet.

**Comment by nolan-veed** [comment]
Of course, we need that too here. I'm on it.

**Comment by gavv** [comment]
@nolan-veed FYI: today arena guards have caught a bug! :)

**Comment by nolan-veed** [comment]
> @nolan-veed FYI: today arena guards have caught a bug! :)

I can finally have some closure! Just kidding... xD
Good to know - and thanks for informing me.
