### ISSUE TITLE
Move implementation of AlignOps and EndianOps to .cpp files

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#601]
In [AlignOps](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_core/align_ops.h) and [EndianOps](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_core/endian_ops.h), move implementations of all non-template methods to .cpp file.

**Comment by gavv** [comment]
@nolan-veed FYI: I looked at AlignOps and MemoryOps once more, and they seem pretty different so probably it's better to keep them separate for now.

**Comment by nolan-veed** [comment]
> @nolan-veed FYI: I looked at AlignOps and MemoryOps once more, and they seem pretty different so probably it's better to keep them separate for now.

I agree.

**Comment by nolan-veed** [comment]
I'll do this one.

**Comment by gavv** [comment]
Thanks!
