### ISSUE TITLE
Optimize StringList iteration

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#617]
[StringList](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_core/string_list.h) implements dynamically extended list of C strings.

Internally, it's just a continuous array. When you append a string to the list, it is copied to the end of array.

It supports iteration via nextof() method (similar to List::nextof and Hashmap::nextof).

Currently nextof() uses strlen() to find position of next string. I**t would be nice to avoid strlen() call for faster iteration**. We can do it by prepending string size before each string stored in list. When nextof() is called, it can lookup this size and just add it to the string pointer.

**In addition, it would be nice to add prevof() method**, that will return element previous to given one, or NULL for the first element.

**Comment by ForeverASilver** [comment]
@gavv 
I can work on this task

**Comment by gavv** [comment]
You're welcome!

**Comment by gavv** [comment]
Merged!
