### ISSUE TITLE
Add android ndk 26 to CI

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#635]
Currently CI checks build with NDK 21 and NDK 25. We need to add NDK 26:

1. In [dockerfiles](https://github.com/roc-streaming/dockerfiles) repo, add `ndk26` tag to [toolchain-linux-android](https://github.com/roc-streaming/dockerfiles/tree/main/images/toolchain-linux-android) image. We need to add en entry to images.csv and ensure that everything builds well.

2. In main repo, update [build.yml](https://github.com/roc-streaming/roc-toolkit/blob/develop/.github/workflows/build.yml):

   - in `android-linux` job, modify matrix to check both ndk21 and ndk26 (for all ABIs)
   - in `android-macos` job, just switch from ndk 25 to ndk 26

Related docs:

* https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/development/continuous_integration.rst
* https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/portability/cross_compiling.rst

**Comment by emmhuber** [comment]
Hello, I will attempt to solve this!
