### ISSUE TITLE
Add arm gcc-10.3 toolchains to CI

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#636]
In [build.yml](https://github.com/roc-streaming/roc-toolkit/blob/develop/.github/workflows/build.yml), in `linux-arm` job, we use `toolchain-aarch64-linux-gnu:gcc-7.4` and `toolchain-arm-linux-gnueabihf:gcc-4.9` dockerfiles to test cross-compilation for arm64 and arm32.

It would be useful to cover more gcc versions:

* [x] `toolchain-aarch64-linux-gnu`
   * [x] `gcc-7.4` (already covered)
   * [x] `gcc-10.3`
* [x] `toolchain-arm-linux-gnueabihf`
   * [x] `gcc-4.9` (already covered)
   * [x] `gcc-7.4`
   * [x] `gcc-10.3`

Corresponding docker tags (`gcc-7.4`, `gcc-10.3`) are already available, we just need to update job matrix and ensure that everything builds without errors.

Note: in `gcc-10.3`, toolchain prefix (which we pass to scons via `--host` option in `scripts/ci_checks/linux-arm`) changed from `aarch64-linux-gnu` to `aarch64-none-linux-gnu` and from `arm-linux-gnueabihf` to `arm-none-linux-gnueabihf`.

Related docs:

* https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/development/continuous_integration.rst
* https://github.com/roc-streaming/roc-toolkit/blob/develop/docs/sphinx/portability/cross_compiling.rst

**Comment by adrianopol** [comment]
#742
