### ISSUE TITLE
Split main() into a few functions

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#656]
CLI tools main() became too large and needs refactoring. We could extract several functions, e.g.: building io config, building pipeline config, running pump.

This should be done for all three tools: `roc-send`, `roc-recv`, `roc-copy`.

Code: https://github.com/roc-streaming/roc-toolkit/tree/develop/src/tools
Docs: https://roc-streaming.org/toolkit/docs/manuals.html

**Comment by nolan-veed** [comment]
I'll do.

**Comment by gavv** [comment]
Great!

**Comment by nolan-veed** [comment]
I'm having a hard time understanding the dependencies. I'm looking at roc_send main.cpp for example.

Various objects needs to be setup using args, and also depend on each other. So, any pointers on how to approach this will help. Right now, I'm a bit lost.

**Comment by gavv** [comment]
Yeah, that code definitely needs more love. Here is a little overview, HTH, and hopefully your refactoring will make it clearer.

High level goal of roc-send and roc-recv is to build source, sink, and pump.

Source is from where you can read samples. Sink is where you can write samples. Pump transfers samples from source to sink.

In roc-send, source is implemented by roc_sndio, and reads samples from file or device. And sink is provided by roc_node, specifically node::Sender, which sends samples written to it to remote receiver. 

Internally, node::Sender creates pipeline (pipeline::SenderLoop) and network loop (netio::NetworkLoop) and connects them together.

pipeline::SenderLoop implements sink interface. When you write samples to it, it produces packets, which are then written to network loop and queued for sending.

main() builds two configs: pipeline::SenderConfig (for sending sink) and sndio::Config (for file/device source). I think building these two configs can be extracted into two functions. 

Then main() parses endpoints and tells node::Sender to use them. This probably can also be extracted into a function.

The, finally, main() constructs Pump and tells it to transfer samples from source to sink. This can become a function as well.

Feel free to ask specific questions if you'll have more.

See also https://github.com/roc-streaming/roc-toolkit/blob/develop/docs%2Fsphinx%2Finternals%2Faudio_backends.rst

and https://roc-streaming.org/toolkit/docs/internals/code_structure.html

**Comment by nolan-veed** [comment]
Hey, thanks for the pointers. I didn't manage to spend a lot of time last month, so I'm looking at this now.

**Comment by gavv** [comment]
Cool, welcome back! :)

**Comment by gavv** [comment]
Implemented, see https://github.com/roc-streaming/roc-toolkit/pull/710#issuecomment-2345684861
