### ISSUE TITLE
Implement List pop_front() and pop_back()

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#667]
[core::List](https://github.com/roc-streaming/roc-toolkit/blob/develop/src%2Finternal_modules%2Froc_core%2Flist.h) has push_front() and push_back().

It would be convenient to have two complementary methods:

```c
void pop_front();
void pop_back();
```

New methods should be covered with tests.

**Comment by as4456** [comment]
I am new to open source contributions and would to pick this item if it hasn't been picked yet.

**Comment by eli-johnson-04** [comment]
I would like to pick up this issue if it hasn't been assigned yet.

**Comment by gavv** [comment]
You're welcome, thanks!

**Comment by spausum** [comment]
If this issue is still open, I would love to take a crack at it.

**Comment by gavv** [comment]
@spausum Hi, thanks, it's assigned actually and there is a linked PR (see above).

**Comment by gavv** [comment]
Landed.
