### ISSUE TITLE
Implement Array pop_back()

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#668]
[core::Array](https://github.com/roc-streaming/roc-toolkit/blob/develop/src%2Finternal_modules%2Froc_core%2Farray.h) has push_back() method.

It would be convenient to add complementary method:

```c
void pop_back();
```

New method should be covered with tests.

**Comment by anurag10** [comment]
Would like to pick this too because it seems a dependency for my another task [#issue 669](https://github.com/roc-streaming/roc-toolkit/issues/669)

**Comment by gavv** [comment]
Thanks!
