### ISSUE TITLE
Implement Array front() and back()

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#670]
[core::List](https://github.com/roc-streaming/roc-toolkit/blob/develop/src%2Finternal_modules%2Froc_core%2Flist.h), [core::Hashmap](https://github.com/roc-streaming/roc-toolkit/blob/develop/src%2Finternal_modules%2Froc_core%2Fhashmap.h) and other classes in roc_core have front() and back() methods.

It would be nice to add front() and back() to [core::Array](https://github.com/roc-streaming/roc-toolkit/blob/develop/src%2Finternal_modules%2Froc_core%2Farray.h) too.

Unlike List, Array holds values, not pointers, so these methods should return references, not pointers. They should panic if array is empty.

New methods should be covered with tests.

**Comment by jlofti** [comment]
Hi I'd like to take this. Have working experience with C++, but want to contribute to open source. Thanks!

**Comment by khansamad47** [comment]
@gavv would like to work on this one if not already assigned.

**Comment by gavv** [comment]
Sure, thanks!

**Comment by gavv** [comment]
Landed
