### ISSUE TITLE
Support pause/resume in SoxSink

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#679]
In [SoxSink](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_sndio/target_sox/roc_sndio/sox_sink.h), implement pause()/resume() methods same way as it's done in [SoxSource](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_sndio/target_sox/roc_sndio/sox_source.h) (i.e.: if device is not file, close it in pause, and reopen in resume; for files, do nothing).

**Comment by aminkhalsi** [comment]
Hi! I'd like to work on this issue if it's still unassigned.
