### ISSUE TITLE
Implement List::insert_after()

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#682]
[core::List](https://github.com/roc-streaming/roc-toolkit/blob/develop/src%2Finternal_modules%2Froc_core%2Flist.h) has insert_before() method.

It would be convenient to implement complementary insert_after().

New method should be covered with tests.

**Comment by veronikaro** [comment]
Could you please assign me?

**Comment by gavv** [comment]
Welcome, thanks!

**Comment by gavv** [comment]
Landed.
