### ISSUE TITLE
Add unit tests for core::RingQueue

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#726]
Cover [RingQueue](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_core/ring_queue.h) with tests.

[test_array.cpp](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/tests/roc_core/test_array.cpp) can be used as an example.

**Comment by mihir-mihir** [comment]
I can work on this!

**Comment by gavv** [comment]
Great, thanks!

**Comment by gavv** [comment]
Landed.
