### ISSUE TITLE
Add IDevice::close()

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#748]
Implement explicit closing of devices & files.

[sndio::IDevice](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_sndio/idevice.h) is an interface implemented by audio devices and files and network senders and receivers. See [doxygen](https://roc-streaming.org/toolkit/doxygen/classroc_1_1sndio_1_1IDevice.html). Currently devices perform closing in their destructor. We need to be able to do it explicitly before calling destructor. This is needed for #677.

Steps:

* add `virtual status::StatusCode close() = 0` to sndio::IDevice
* add this method to all IDevice implementations
* in implementations in roc::sndio, move closing of file/device from destructor to close(); and in destructor call roc_panic() if close() was not called
* in implementation in roc::pipeline, close() may be no-op (just return StatusOK)
* sndio::Pump should invoke close() before exiting from run()

Related: #703.

**Comment by runei** [comment]
Hi, I am interested in solving this issue.

**Comment by gavv** [comment]
Thanks, Leonardo! Be sure to pull fresh develop, it has some recent changes in IDevice.

**Comment by runei** [comment]
Hi @gavv , what status code should it return in case the device does not close successfully? Or it always return StatusOK?

**Comment by gavv** [comment]
> Hi @gavv , what status code should it return in case the device does not close successfully? Or it always return StatusOK?

Same as from write - ErrFile or ErrDevice depending on device type.
