### ISSUE TITLE
Implement moving percentile algorithm 

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-toolkit#751]
Add a class that implements moving percentile algorithm based on these excellent articles:

* [Fast implementation of the moving quantile based on the partitioning heaps](https://aakinshin.net/posts/partitioning-heaps-quantile-estimator/)
* [Better moving quantile estimations using the partitioning heaps](https://aakinshin.net/posts/partitioning-heaps-quantile-estimator2/)

(Also feel free to suggest a better approach if you know one).

The new class can be named MovQuantile or MovPercentile. Interface should be similar to [core::MovStats](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/internal_modules/roc_core/mov_stats.h) class, which implements moving minimum, maximum, and variance.

We also need unit tests, you can find example [here](https://github.com/roc-streaming/roc-toolkit/blob/develop/src/tests/roc_core/test_mov_stats.cpp).

This task is needed for #712.

**Comment by novertia** [comment]
Hi can I work on this issue

**Comment by gavv** [comment]
Sure, thanks!

**Comment by gavv** [comment]
Merged
